
const data = {

    products: [
      {  id:1,
        name: 'Free Shirt',
        slug: 'free-shirt',
        category: 'Shirts',
        image: 'https://d30fs77zq6vq2v.cloudfront.net/product/515x772/18102022/23708_273_1666074986_634e496a18f98-1364490385924.jpg',
        price: 8800,
        discount: 6799,
        percentage: 25,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 8,
        countInStock: 20,
        description: 'Adorn Yourself With This Breathtaking Outfit. A Delicate Shirt Made Of Organza Fabric In Soft Serial Pink Color Is Beautifully Designed With The Same Color Embroidery, Fully Embroidered Sleeves Delicately Embroidered In The Thread, And Sequins With A Delicate Border Running Along The Hemline. Its Enhanced With A Net Dupatta With Patches On The Border. It Will Make You Look Like A Complete Goddess!',
        
      },
      {
        id:2,
        name: 'Fit Shirt',
        slug: 'fit-shirt',
        category: 'Shirts',
        image: 'https://d30fs77zq6vq2v.cloudfront.net/product/515x772/18102022/23715_945_1666073888_634e45207aa38-198061919822.jpg',
        price: 8800,
        discount: 6799,
        percentage: 25,
        brand: 'Adidas',
        rating: 3.2,
        numReviews: 10,
        countInStock: 20,
        description: 'Adorn Yourself With This Breathtaking Outfit. A Delicate Shirt Made Of Organza Fabric In Soft Serial Pink Color Is Beautifully Designed With The Same Color Embroidery, Fully Embroidered Sleeves Delicately Embroidered In The Thread, And Sequins With A Delicate Border Running Along The Hemline. Its Enhanced With A Net Dupatta With Patches On The Border. It Will Make You Look Like A Complete Goddess!',
      },
      {
        id:3,
        name: 'Slim Shirt',
        slug: 'slim-shirt',
        category: 'Shirts',
        image: 'https://d30fs77zq6vq2v.cloudfront.net/product/515x772/18102022/23714_961_1666074402_634e4722815d2-1361855159570.jpg',
        price: 8800,
        discount: 6799,
        percentage: 25,
        brand: 'Raymond',
        rating: 4.5,
        numReviews: 3,
        countInStock: 20,
        description: 'Adorn Yourself With This Breathtaking Outfit. A Delicate Shirt Made Of Organza Fabric In Soft Serial Pink Color Is Beautifully Designed With The Same Color Embroidery, Fully Embroidered Sleeves Delicately Embroidered In The Thread, And Sequins With A Delicate Border Running Along The Hemline. Its Enhanced With A Net Dupatta With Patches On The Border. It Will Make You Look Like A Complete Goddess!',
      },
      {
        id:4,
        name: 'Golf Pants',
        slug: 'golf-pants',
        category: 'Pants',
        image: 'https://d30fs77zq6vq2v.cloudfront.net/product/515x772/24092022/23743_731_1664016645_632ee10591414-1151814535799.jpg',
        price: 8800,
        discount: 6799,
        percentage: 25,
        brand: 'Oliver',
        rating: 2.9,
        numReviews: 13,
        countInStock: 20,
        description: 'Adorn Yourself With This Breathtaking Outfit. A Delicate Shirt Made Of Organza Fabric In Soft Serial Pink Color Is Beautifully Designed With The Same Color Embroidery, Fully Embroidered Sleeves Delicately Embroidered In The Thread, And Sequins With A Delicate Border Running Along The Hemline. Its Enhanced With A Net Dupatta With Patches On The Border. It Will Make You Look Like A Complete Goddess!',
      },
      {
        id:5,
        name: 'Fit Pants',
        slug: 'fit-pants',
        category: 'Pants',
        image: 'https://d30fs77zq6vq2v.cloudfront.net/product/515x772/18102022/23713_799_1666074727_634e486732a86-1551519149169.jpg',
        price: 8800,
        discount: 6799,
        percentage: 25,
        brand: 'Zara',
        rating: 3.5,
        numReviews: 7,
        countInStock: 20,
        description: 'Adorn Yourself With This Breathtaking Outfit. A Delicate Shirt Made Of Organza Fabric In Soft Serial Pink Color Is Beautifully Designed With The Same Color Embroidery, Fully Embroidered Sleeves Delicately Embroidered In The Thread, And Sequins With A Delicate Border Running Along The Hemline. Its Enhanced With A Net Dupatta With Patches On The Border. It Will Make You Look Like A Complete Goddess!',
      },
      {
        id:6,
        name: 'Classic Pants',
        slug: 'classic-pants',
        category: 'Pants',
        image: 'https://d30fs77zq6vq2v.cloudfront.net/product/515x772/18102022/23688_193_1666074274_634e46a20286d-1008473570054.jpg',
        price: 8800,
        discount: 6799,
        percentage: 25,
        brand: 'Casely',
        rating: 2.4,
        numReviews: 14,
        countInStock: 20,
        description: 'Adorn Yourself With This Breathtaking Outfit. A Delicate Shirt Made Of Organza Fabric In Soft Serial Pink Color Is Beautifully Designed With The Same Color Embroidery, Fully Embroidered Sleeves Delicately Embroidered In The Thread, And Sequins With A Delicate Border Running Along The Hemline. Its Enhanced With A Net Dupatta With Patches On The Border. It Will Make You Look Like A Complete Goddess!',
      },
    ],
  };
  
  export default data;